In [1]:
import pandas as pd
import numpy  as np

In [3]:
region_a = pd.read_csv("order_region_a.csv")
region_a.head()

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764

In [6]:
region_b = pd.read_csv("order_region_b.csv")
region_b.head()

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764

In [15]:
region_a.shape, region_b.shape

((44494, 6), (44494, 6))

In [10]:
region_a.describe()

        OrderItemId  QuantityOrdered     ItemPrice      batch_id
count  4.449400e+04     44494.000000  44494.000000  44494.000000
mean   3.519289e+13         1.028768    762.276240    528.722794
std    2.034514e+13         0.390857    576.166402    434.141238
min    2.019231e+09         0.000000    159.000000      1.000000
25%    1.765068e+13         1.000000    499.000000    170.250000
50%    3.505495e+13         1.000000    549.000000    399.000000
75%    5.289352e+13         1.000000    799.000000    823.000000
max    7.036660e+13        30.000000  12686.400000   2450.000000

In [23]:
region_b.describe()

        OrderItemId  QuantityOrdered     ItemPrice      batch_id
count  4.449400e+04     44494.000000  44494.000000  44494.000000
mean   3.519289e+13         1.028768    762.276240    528.722794
std    2.034514e+13         0.390857    576.166402    434.141238
min    2.019231e+09         0.000000    159.000000      1.000000
25%    1.765068e+13         1.000000    499.000000    170.250000
50%    3.505495e+13         1.000000    549.000000    399.000000
75%    5.289352e+13         1.000000    799.000000    823.000000
max    7.036660e+13        30.000000  12686.400000   2450.000000

In [17]:
region_a['Region'] = 'A'
region_b['Region'] = 'B'

In [80]:
total_sale = region_a.append(region_b)
total_sale

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,Region
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,A
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,A
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,A
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,A
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,A
...,...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729,B
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151,B
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54,B
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401,B
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461,B

In [81]:
total_sale[total_sale['OrderId']=='171-0192979-5021168']

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,Region
317,171-0192979-5021168,1.739590e+13,1,1614.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",103,A
318,171-0192979-5021168,1.739590e+13,1,1614.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",113,A
319,171-0192979-5021168,1.739590e+13,1,1614.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",369,A
317,171-0192979-5021168,1.739590e+13,1,1614.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",103,B
318,171-0192979-5021168,1.739590e+13,1,1614.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",113,B
319,171-0192979-5021168,1.739590e+13,1,1614.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",369,B

In [78]:
total_sale = total_sale.drop_duplicates(subset=['OrderId','Region'])

In [67]:
total_sale['total_sales'] = total_sale['QuantityOrdered'] * total_sale['ItemPrice']
total_sale

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,Region,total_sales
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,A,949.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,A,699.0
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,A,399.0
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,A,499.0
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,A,1699.0
...,...,...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729,B,899.0
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151,B,499.0
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54,B,499.0
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401,B,499.0
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461,B,629.0

In [68]:
total_sale['PromotionDiscount'] = total_sale['PromotionDiscount'].str.extract('([-+]?\d*\.?\d+)').astype(float)

In [69]:
total_sale.PromotionDiscount.unique()

array([10. , 10.1])

In [70]:
total_sale['Net_sale'] = total_sale['total_sales'] - total_sale['PromotionDiscount']

In [71]:
total_sale = total_sale[total_sale['Net_sale']>0]

In [72]:
total_sale[total_sale['Net_sale']<=0].shape

(0, 9)

In [73]:
total_sale.to_csv('Total_sales.csv', index=False)

In [74]:
total_sale

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,Region,total_sales,Net_sale
0,171-0001135-1657958,1.116890e+13,1,949.0,10.0,359,A,949.0,939.0
1,171-0001497-9165123,1.976030e+13,1,699.0,10.1,1135,A,699.0,688.9
2,171-0002127-1363507,5.949760e+12,1,399.0,10.0,297,A,399.0,389.0
3,171-0002370-0601169,5.757190e+13,1,499.0,10.1,114,A,499.0,488.9
4,171-0004526-2028348,3.385130e+13,1,1699.0,10.0,764,A,1699.0,1689.0
...,...,...,...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,10.1,729,B,899.0,888.9
44490,403-9398429-3695549,5.373600e+13,1,499.0,10.0,151,B,499.0,489.0
44491,403-9399318-8267565,7.727720e+12,1,499.0,10.1,54,B,499.0,488.9
44492,403-9400326-2753965,2.029820e+13,1,499.0,10.0,1401,B,499.0,489.0
44493,403-9400753-7822741,6.437950e+12,1,629.0,10.1,461,B,629.0,618.9

In [79]:
total_sale[total_sale['OrderId']=='171-0192979-5021168']

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,Region,total_sales,Net_sale
317,171-0192979-5021168,1.739590e+13,1,1614.0,10.1,103,A,1614.0,1603.9
317,171-0192979-5021168,1.739590e+13,1,1614.0,10.1,103,B,1614.0,1603.9